### ISSUE TITLE
Not getting the instance url from the 'password authentication mode'

### ISSUE THREAD

**Issue by matthewcard23** [pozil/salesforce-node-client#1]
Hi,

I'm having an issue where i'm getting the payload object returned without an instance url when trying to password authenticate. I don't want the users of my app to have to login through salesforce but instead provide my own credentials as you've highlighted in your 'password authentication mode'. 

Here is my code so far:
```javascript
var sfdcConfig = {
      // OAuth2 service
      auth : {

        domain : 'https://test.salesforce.com',

        callbackUrl : 'http://localhost:5000/auth/callback',

        consumerKey : '<consumer key>',
        consumerSecret : '<consumer secret>',
      },
      // Data service
      data : {
        // Force.com API version
        apiVersion : 'v1.0'
      }
    };

    var SalesforceClient = require('salesforce-node-client');

    // Instantiate Salesforce client with configuration
    var sfdc = new SalesforceClient(sfdcConfig);

    sfdc.auth.password({
      'username': '<username>',
      'password': '<password>',
}, function(error, payload) {
    // Store the payload content in a server-side session
      if (!error && payload) {
        storage.set('session',payload);
      }
    });

    var sfdcSession = storage.get('session');
    var query = encodeURI("<my query here>");
    var apiRequestOptions = sfdc.data.createDataRequest(sfdcSession, 'query?q='+ query);

    httpClient.get(apiRequestOptions, function (error, payload) {
      if (!error && payload) {
        data = JSON.parse(payload);
      if (data) {
        storage.set('data',data);
        cb(null, data);
      } else {
           cb(true, null);
         }
       } else {
        cb(true, null);
        }
     });
```
Any help or pointers would be extremely useful. I'm new to React and Salesforce so still learning the ropes.

Thanks,
Matt

**Comment by pozil** [comment]
Hi Matt,

I am on holiday this week so I can't test your code right now.

I do see a problem in the sample you sent: the apiVersion shouldn't be v1.0
it should be v41.0 (current Salesforce release also know as Winter '18).

Try to update your code with that and be more specific on the error that
you get (error message,stack trace...).

Cheers,

Philippe

**Comment by matthewcard23** [comment]
Hi Phillippe,

I'll give that a try and see how I get on. Thanks very much for getting back to me.

Cheers,
Matt

**Comment by matthewcard23** [comment]
I think i've found the issue. It's that i'm not passing headers to enable for CORS. 

I'm getting this error: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:5000' is therefore not allowed access. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

Is there a way to add headers to your requests?

Thanks,
Matt

**Comment by pozil** [comment]
Sure, I am using the [request](https://www.npmjs.com/package/request) library to perform HTTP requests.

You can modify the request options and add custom headers like so:
https://www.npmjs.com/package/request#custom-http-headers

Going back to the sample code, you should write something like this:

```js
// Get a pre-configured request configuration
var apiRequestOptions = sfdc.data.createDataRequest(sfdcSession, 'query?q='+ query);

// Update request configuration by adding custom headers
apiRequestOptions.headers['Access-Control-Request-Method'] = 'GET';
...

// Perform GET request
httpClient.get(apiRequestOptions, function (error, payload) {
...
}
```

**Comment by matthewcard23** [comment]
My issue seems to be adding headers to the password authentication request. Can I just add headers to the part where the username and password are or do I need to add a section for headers in the sfdcConfig section?

Thanks again for all your help.

**Comment by pozil** [comment]
Yes, you are right, I missed this requirement in my design.
There is currently no way to pass custom headers to the authentication request without modifying the library.

As you suggested these extra headers should be part of the sfdcConfig options.
PR welcome if you have time :)

**Comment by matthewcard23** [comment]
I'll have a look at modifying it and i'll get back to you. Thanks for all your feedback Philippe.

**Comment by Juggo** [comment]
@matthewcard23 how did you solve it eventually?

**Comment by matthewcard23** [comment]
@Juggo I'm currently attempting a different way (to save time for my solution) if that doesn't work i'll be looking at a fix for this issue. I'll let you know.

**Comment by matthewcard23** [comment]
@Juggo I've managed to get rid of the CORS errors by adding some headers to the callService function in the oauth2.js file located in Philippe's salesforce-node-client files. This function is called by the password authentication. The Request module allows for custom headers so an example are the ones i've added like so:

```javascript
function callService(serviceUrl, options, callback) {
  var uri = buildServiceUrl(serviceUrl, options);
  var headers = {
    headers: {
      //Origin is your domain or in my case my localhost area, IP address and port number
      'Access-Control-Allow-Origin':  '<origin>',
      'Access-Control-Allow-Methods': 'POST',
      'Access-Control-Allow-Headers': 'Content-Type, Authorization'
    }
  };

  httpClient.post(headers, {
    url: uri,
    proxy: proxyUrl
  }
```

I'm still having further issues with my solution but this seems to have fixed the CORS issue. Hope this helps.

Thanks,
Matt
