### ISSUE TITLE
Login with session id of outbound message

### ISSUE THREAD

**Issue by guilhermemvo** [pozil/salesforce-node-client#7]
It's possible get data from salesforce only with session id of outbound message?

**Comment by pozil** [comment]
@guilhermemvo sorry but this is not supported by my client: Outbound Messages rely on SOAP and my client only supports REST. Also, this client relies on OAuth authentication but Outbound Messages do not.
FYI: there might be other technical issues with Outbound Messages but I a have no experience with them.
